import AllProviders from "@/components/AllProviders";
import LayoutContainer from "@/components/layout/LayoutContainer";
import { Work_Sans } from 'next/font/google'

import "./globals.css";

const workSans = Work_Sans({
  subsets: ["latin"],
  display: 'swap',
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={workSans.className}>
      <head>
        <title>Nextjs Blog Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="emotion-insertion-point" content="" />
      </head>
      <body className={workSans.className} style={{ 
        backgroundImage: `url("/images/background-img.png")`,
        backgroundSize: '170px 170px',
        backgroundPosition: 'center',    
        backgroundRepeat: 'repeat'    
        }}>
        <AllProviders>
          <LayoutContainer>{children}</LayoutContainer>
        </AllProviders>
      </body>
    </html>
  );
}
